
"set colorscheme
colorscheme molokai

"set the no vi combatible
set nocompatible


"begin pathogen
execute pathogen#infect()

"set commande aliases
:command Cterm ConqueTerm bash
:command Ctermsplit ConquTermSplit bash
:command Ctermvsplit ConqueTermVSplit bash
:command W w
:command Tab s/\t/    /g

" set leader key to \
let mapleader = "\\"

"nunmap <leader>s

"set leader key mappings
nmap <leader>c :Ctermvsplit<cr>
nmap <leader>n :NERDTreeToggle<cr>
nmap <leader>v :vsplit $MYVIMRC<cr>
"nmap <leader>sv :source $MYVIMRC<cr>

"set syntax
syntax on

"set tab size to 4
set tabstop=4
set ts=4
set softtabstop=4
set shiftwidth=4
set expandtab
"set smarttab
set smartindent


" auto indent
set autoindent

" This is for filetype specific behavior (i.e. python is different than c++)
filetype indent plugin on

" turn on line numbers
set number


" chage vimdiff colors
"if &diff
    highlight DiffAdd ctermbg=red ctermfg=black
    highlight DiffChange ctermbg=red ctermfg=black
    highlight DiffDelete ctermbg=red ctermfg=black
"endif
    

" set folding
set foldmethod=indent
"set foldnestmax=2
set nofoldenable


" save foldings
au BufWinLeave * silent! mkview
au BufWinenter * silent! loadview
